fundus/config/routes.rb
Rails.application.routes.draw do
  devise_for :dusers
  root to: "static_pages#index"
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  get "/signup", to: "users#new"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"
  get "/login", to: "sessions#new"

  post "/signup", to: "users#create"
  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  resources :users
end

fundus/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize duser
    can :read, :all
    return unless duser.present? && duser.admin?
    can :access, :rails_admin
    can :read, :dashboard
    if duser.admin?
      can :manage, :all
    elsif duser.founder?
      can :manage, %i(event foundation)
    elsif duser.simple_user?
      can :update, :blog
    end
  end
end

fundus/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fundus/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

fundus/app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
end

fundus/app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :causes, dependent: :destroy
  has_many :events, dependent: :destroy
end

fundus/app/models/cause.rb
class Cause < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :donation, dependent: :destroy
end

fundus/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

fundus/app/models/d_user.rb
class DUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

fundus/app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :cause
end

fundus/app/models/duser.rb
class Duser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  public
  def simple_user?
    return true if role == 0
    false
  end

  def founder?
    return true if role == 1
    false
  end

  def admin?
    return true if role == 2
    false
  end
end

fundus/app/models/duser_ability.rb
class DuserAbility
  include CanCan::Ability

  def initialize duser
    can :read, :blog
    if duser.admin?
      can :access, :rails_admin
      can :read, :dashboard
      can :manage, :all
    elsif duser.founder?
      can :access, :rails_admin
      can :read, :dashboard
      can :manage, [Event, Cause]
    elsif duser.simple_user?
      can :access, :rails_admin
      can :read, :dashboard
      can [:read, :create, :update], Blog
    end
  end
end

fundus/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :attendances, dependent: :destroy
  has_many :attendedusers, through: :attendances, source: :user
end

fundus/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

fundus/app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :causes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
           foreign_key: "follower_id",dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
           foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :attendances, dependent: :destroy
  has_many :attendedevents, through: :attendances, source: :event

  before_save {email.downcase!}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 6}

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

fundus/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

fundus/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by id: params[:id]
    if @user.update_attributes user_params
      flash[:success] = "Profile update"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

fundus/app/helpers/application_helper.rb
module ApplicationHelper
  def log_in user
    session[:user_id] = user.id
  end
end

fundus/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

fundus/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

fundus/app/helpers/users_helper.rb
module UsersHelper
end

fundus/app/views/layouts/_footer.html.erb
<!-- Start of footer section
  ============================================= -->
  <footer id="footer-section" class="footer-style">
    <div class="footer-overlay">
      <div class="footer-contact-content-1">
        <div class="container">
          <div class="row">
            <div class="footer-contact-content">
              <div class="row">
                <div class="col-sm-2 col-xs-5">
                  <div class="footer-contact-info">
                    <ul class="footer-contact-info-list">
                      <li><span class="pull-left icon ti-comments-smiley"></span><span class="info-details text-uppercase">call us</span><p>560 265 1523</p></li>
                    </ul>
                  </div>
                </div>
                <div class="col-sm-3 col-xs-5">
                  <div class="footer-contact-info">
                    <ul class="footer-contact-info-list">
                      <li><span class="pull-left icon ti-comments"></span><span class="info-details text-uppercase">PLEASE</span><p>GET CALL BACK</p></li>
                    </ul>
                  </div>
                </div>
                <div class="footer-social pull-right mt10">
                  <div class="social">
                    <ul class="social-list">
                      <li><a href="#"><span class="ti-facebook"></span></a></li>
                      <li><a href="#"><span class="ti-twitter"></span></a></li>
                      <li><a href="#"><span class="ti-google"></span></a></li>
                      <li><a href="#"><span class="ti-instagram"></span></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /footer-contact-1 -->

      <div class="footer-main-content">
        <div class="container">
          <div class="row">
            <div class="footer-main-content-area pt75">
              <div class="row">
                <div class="col-sm-3">
                  <div class="footer-logo pb20">
                    <a  href="home-1.html"><%= image_tag src="f-logo.png" %></a>
                  </div>
                  <div class="footer-text">
                    <p>Lorem ipsum dolor sit ametlyeolo consectetur adipisicing elit sed dong eiusmod tempor incididunt ut labore et incididunt.  </p>
                  </div>
                  <div class="footer-text">
                    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco. </p>
                  </div>
                </div>
                <!-- /col-sm-3 -->

                <div class="col-sm-3">
                  <div class="footer-head-title text-uppercase pb35">
                    <h2 class="widgettitle">RECENT TWEET</h2>
                  </div>
                  <!-- /title -->
                  <div class="recent-tweet-list">
                    <div class="tweet-icon pull-left mr20">
                      <span class="red ti-twitter"></span>
                    </div>
                    <div class="tweet-text">
                      <span class="name-tweet"><a class="" href="#">@tonmoymishal</a></span>
                      <span class="tweet-content">Excepteur sint occ aecat cupidatat </span>
                      <span class="red tweet-link"><a href="#">goo.gl/GjFUTp</a></span>
                      <span class="tweet-time">45 min ago</span>
                    </div>
                  </div>
                  <!-- /list -->

                  <div class="recent-tweet-list mt10">
                    <div class="tweet-icon pull-left mr20">
                      <span class="red ti-twitter"></span>
                    </div>
                    <div class="tweet-text">
                      <span class="name-tweet"><a class="" href="#">@tonmoymishal</a></span>
                      <span class="tweet-content">Excepteur sint occ aecat cupidatat </span>
                      <span class="red tweet-link"><a href="#">goo.gl/GjFUTp</a></span>
                      <span class="tweet-time">45 min ago</span>
                    </div>
                  </div>
                </div>
                <!-- /col-sm-3 -->

                <div class="col-sm-3">
                  <div class="footer-head-title text-uppercase pb35">
                    <h2 class="widgettitle">GET IN TOUCH</h2>
                  </div>
                  <!-- /title -->
                  <div class="touch-content">
                    <div class="tweet-text">
                      <span class="name-tweet">Address: </span>
                      <span class="tweet-content">315 Chat mohon Bazar New Yor, NY 4536 </span>
                    </div>
                    <div class="tweet-text mt5">
                      <span class="name-tweet">E-mail: </span>
                      <span class="tweet-content">support@yourdomain.com </span>
                    </div>
                    <div class="tweet-text mt5">
                      <span class="name-tweet">Phone: </span>
                      <span class="tweet-content">560 265 1523</span>
                    </div>
                    <div class="newsletter-form">
                      <form action="#" method="get" class="nwsltter">
                        <div class="form-group">
                          <input type="email" name="email" placeholder="Your Email" class="form-control">
                        </div>
                      </form>
                      <div class="submit-btn">
                        <button type="submit" value="Submit"><%= image_tag src="inbox.png" %></button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /col-sm-3 -->

                <div class="col-sm-3">
                  <div class="footer-head-title text-uppercase pb35">
                    <h2 class="widgettitle">GALLERY</h2>
                  </div>
                  <div class="footer-gallery pb35">
                    <ul class="footer-gallery">
                      <li><a href="#"><%= image_tag src="g-1.png" %></a></li>
                      <li><a href="#"><%= image_tag src="g-2.png" %></a></li>
                      <li><a href="#"><%= image_tag src="g-3.png" %></a></li>
                      <li><a href="#"><%= image_tag src="g-4.png" %></a></li>
                      <li><a href="#"><%= image_tag src="g-5.png" %></a></li>
                      <li><a href="#"><%= image_tag src="g-6.png" %></a></li>
                    </ul>
                  </div>
                </div>
                <!-- /col-sm-3 -->
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /footer-main-content -->
      <div class="footer-menu">
        <div class="container">
          <div class="row">
            <div class="footer-menu-content">
              <div class="copy-right pull-left">
                <p>© 2016 <span class="red"><a href="https://www.htmlmate.com/">HTMLmate</a> </span>All right reserved. </p>
              </div>
              <div class="footer-menu-list pull-right mt25">
                <ul class="menu-list">
                  <li><a href="#">Home</a><span>/</span></li>
                  <li><a href="#">Event</a><span>/</span></li>
                  <li><a href="#">Cause</a><span>/</span></li>
                  <li><a href="#">FAQ</a><span>/</span></li>
                  <li><a href="#">Support</a><span></span></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- End of footer section

fundus/app/views/layouts/_header.html.erb
  <header>
    <div class="header-top-bg">
      <div class="container">
        <div class="row">
          <div class="header-top">
            <div class="head-top-info pull-left">
              <ul class="top-info">
                <li><%= image_tag src="call.png" %>05. 256. 8942</li>
                <li><%= image_tag src="inbox.png" %>info@fundme.com</li>
              </ul>
            </div>
            <!-- /head-top-info -->
            <div class="header-social pull-right">
              <div class="social">
                <ul class="social-list">
                  <li><a href="#"><span class="ti-facebook"></span></a></li>
                  <li><a href="#"><span class="ti-twitter"></span></a></li>
                  <li><a href="#"><span class="ti-google"></span></a></li>
                  <li><a href="#"><span class="ti-instagram"></span></a></li>
                </ul>
              </div>
            </div>
            <!-- /header-social -->
          </div><!-- /header-top -->
        </div><!-- /row -->
      </div><!-- /container -->
    </div>
    <div class="menu-bar">
      <div class="container">
        <div class="row">
          <nav class="navbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <a class="navbar-brand" href="home-1.html"><%= image_tag src="logo.png" %></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="index.html">Home</a></li>
                <li><a href="cause.html">Causes</a>
                  <ul class="menu-dropdown">
                    <li><a href="cause.html">Causes</a></li>
                    <li><a href="cause-single.html">Causes Details</a></li>
                  </ul>
                </li>
                <li><a href="event.html">Events</a>
                  <ul class="menu-dropdown">
                    <li><a href="event.html">Events</a></li>
                    <li><a href="event-single.html">Events Details</a></li>
                  </ul>
                </li>
                <li><a href="blog-archive.html">Blog</a>
                  <ul class="menu-dropdown">
                    <li><a href="blog-archive.html">Blog Archive</a></li>
                    <li><a href="blog-single.html">Blog Details</a></li>
                  </ul>
                </li>
                <li><a href="#">Pages</a>
                  <ul class="menu-dropdown">
                    <li><a href="contact.html">Contact</a></li>
                    <li><a href="404.html">404</a></li>
                    <li><a href="about.html">About-us</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
            <div class="home-donate donate-btn-1 text-uppercase">
              <a href="donation.html">donate now</a>
            </div>
            <div id="sb-search" class="sb-search " >
                  <form action="#" method="post">
                   <input class="sb-search-input " onkeyup="buttonUp();" placeholder="Enter Your Search Word..." type="search" value="" name="search" id="search">
                 <input class="sb-search-submit" type="submit"  value="">
                 <span class="sb-icon-search"><i class="ti-search"></i></span>
                  </form>
            </div>
          </nav>
          <div class="wrap">
            <!--MENU-->
            <div id="main-menu">
              <div class="menu-btn">
                <div class="menu-btn-line menu-btn-line-1"></div>
                <div class="menu-btn-line menu-btn-line-2"></div>
                <div class="menu-btn-line menu-btn-line-3"></div>
              </div>
              <div class="moduletable_menu">

                <ul class="nav menu">
                  <li><a href="home-1.html">Home</a></li>
                  <li><a href="about-us.html">About</a></li>
                  <li><a href="blog-archive.html">Blog</a></li>
                  <li><a href="blog-single.html">Blog Single</a></li>
                  <li><a href="cause.html">Cause</a></li>
                  <li><a href="cause-single.html">Cause Details</a></li>
                  <li><a href="event.html">Event</a></li>
                  <li><a href="event-single.html">Event Single</a></li>
                  <li><a href="404.html">404</a></li>
                  <li><a href="contact.html">Contacts</a></li>
                </ul>
              </div>
            </div>
            <!-- END menu -->
          </div><!--/wrap  -->
        </div><!--/row  -->
      </div><!--/container  -->
    </div><!--/menu-bar  -->
  </header>
  <!-- End of Header -->

fundus/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

fundus/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fundus || <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% if duser_signed_in? %>
      <p><%= current_duser.id %></p>
    <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render "layouts/footer" %>
  </body>
</html>

fundus/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>